travis:
  secure:
    BINSTAR_TOKEN: vBpB0JyXmvUngxiQSlPgKSfL0h/12M7sztwGlyxIvoZ2/h4d1Zkkhw8pdAdzyok+xLEte1cNRQ/MzMXkFWYBq22CgLVtdxB6MmTJTrNY+CS3lcHPve0YPsrnQZUqyWwfUkMqtJtSfKZykvqw20G82bbF4AGaSsCuVxWO7l1M4cw5zgubNO2otUu4qiHgqDJoRUWqJUgOj6AVHXVl1U2192lK+S7DvAN0VJFHY2E3z7lJsldFMUxEfXU8R7EVVSld+jBYtKIH/PS3EIwPD5+D3REAycq8xM4EVPJRxmC1767hycCLVxVXRkIqgDAAcrKmLGyywORQiJ6nU78owki93yEYQgt3V0qIhNyy1gc4RUsrDMZBdhA7i8HLZuEfMkuFlSBzzoJ1XnIDwlxNpEe0/ahaOPzSMIh6yLeshpnrn1w3tMRy5/CcIHkD0krZjlYtqrAIxsSyu0nFsvnhmG2jc0UMh8A83LQO4CCGm0PBPcepUnYAUCnZr8AM8WxZ1RJDhDBLl1wE0ga7+UAS1ie4p//fdejd53UwkKNg0vN6rWNiaSV+MU5thVMXhhPBquhMAH2NQ+h+Em/9dJjnlp9LrOlSjHSzmN6EXReTrfJ0yN1pwC6c2TtyLnHoAXv/7jsXGVPCrW50CR/5YZmkQ/Z7wBTYon4tzSqNk3asFeashzI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
